### PR TITLE
Feature/carthage

### PR DESCRIPTION
**Pull request by justinmakaila**
This should resolve the issues discussed in #25 and #26. It also removes the need for a Pods/ directory, and makes managing Cocoapods as simple as the `.podspec` and Podfile. Adds a new release; 0.1.4.

### CODE REVIEW

**Comment by justinmakaila** [comment]
This should probably be merged into it's own branch for the time being

**Comment by justinmakaila** [comment]
I'm also going to merge in master, so this should be able to auto merge.

**Comment by justinmakaila** [comment]
I merged `feature/carthage` on my version to master, and then merged this master into my fork. Closing this and submitting a new one.

**Comment by sferoze** [comment]
I've created static frameworks using carthage, and it works fine in the simulator, but the minute you put it on a device it gives the same error "Library not loaded: @rpath/InflectorKit.framework/InflectorKit"

I had changed the frameworks to optional, and thought I had it, but then nothing worked in the app... Any suggestions @justinmakaila ?

**Comment by justinmakaila** [comment]
Add a copy files build phase which copy's the frameworks from the Carthage/build/iOS dir



—Justin Makaila

**Pull request closed without merging**
