### PR TITLE
add ability to include first/last name on signup

### PR DESCRIPTION
**Pull request by alexcorre**
Adding a new method exposed in `METDDPClient+AccountsPassword.h` category that allows signup to include first/last name in addition to email/password.

### CODE REVIEW

**Comment by martijnwalraven** [comment]
There may be additional fields you might want to set on `profile` when creating a user (e.g. school affiliation in my case). In a private branch which I still need to clean up, I've actually added a `signUpWithEmail:password:profile:completionHandler:` method for this purpose, where `profile` takes a dictionary. This seems like a more general mechanism that could either underly your methods or act as an alternative. 

But I don't want to hold you up and I'd be happy to merge your pull request now. Then I could have another look at it when I find the time to merge my changes. Or you could make the changes yourself. Let me know what you prefer.

I'm not sure what the status of this is, but there has been talk of [deprecating profile](https://meteor.hackpad.com/Proposal-for-deprecating-user-profile-3UljX1VayvV). I'm not sure what would happen to `createUser` in this case.

**Comment by alexcorre** [comment]
I like the generic solution of allowing a profile dictionary to be provided: `signUpWithEmail:password:profile:completionHandler:`.  I'll update this PR to use the api you have suggested when I have some time tomorrow and you can merge it in after that. Does that work?

Not sure of how deprecating profile will affect the method. But we can handle that when/if it happens.

**Comment by alexcorre** [comment]
@martijnwalraven I've incorporated your suggestions. Any more feedback here?

**Comment by martijnwalraven** [comment]
Sorry I missed this. Looks great, so I merged it.

**Pull request merged**
